### ISSUE TITLE
Can't start because of missing *.tflite files

### ISSUE THREAD

**Issue by hannesa2** [spokestack/android-control-room#8]
I downloaded missing `*.tflite` files

```
wget https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/detect.tflite -P app/src/main/assets
wget https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/encode.tflite -P app/src/main/assets
wget https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/filter.tflite -P app/src/main/assets
```

But still one is missing

<img width="691" alt="image" src="https://user-images.githubusercontent.com/3314607/115985983-82115a80-a5ae-11eb-8bec-7d2c9dc63c9b.png">

But there is no such file 

`wget https://d3dmqd7cy685il.cloudfront.net/model/wake/spokestack/note.tflite -P app/src/main/assets`

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/3314607/115985999-93f2fd80-a5ae-11eb-8cc2-ee0ac3122c92.png">

**Comment by hannesa2** [comment]
related to https://github.com/spokestack/android-control-room/pull/5#discussion_r619771848

**Comment by hannesa2** [comment]
You are probably a one-man-show that's why I see the need of Espresso tests as well to avoid such errors. Here you can copy&paste it.

https://github.com/hannesa2/LiveEdgeDetection/blob/59e6b39fff91e8cdc06fe3a8995e412f498f0163/.github/workflows/Android-CI-Espresso.yml#L36-L47

**Comment by hannesa2** [comment]
I see more stuff missing
<img width="259" alt="image" src="https://user-images.githubusercontent.com/3314607/115986249-9dc93080-a5af-11eb-9c58-316433ad3bc8.png">

From where I can grab it ?

**Comment by space-pope** [comment]
The lines containing `note` should be deleted, which I'll do in a separate PR. That was a local test that I didn't catch in review.

**Comment by space-pope** [comment]
Actually, I half take that back. Those are for the NLU module, which has been added into the repository, but I'll include a different model and update the README with instructions. Until I'm able to do that properly, here are files you can use to test:

```
https://s.spokestack.io/u/7fYxV/metadata.json
https://s.spokestack.io/u/7fYxV/nlu.tflite
https://s.spokestack.io/u/7fYxV/vocab.txt
```
and change the setup code in `buildSpokestack()` to use those instead of the `note` versions.
